services:
  - type: web
    name: chat-nova-fd
    runtime: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html